//! Property tests for the three invariants that must never break.
//!
//! 1. **Chips are conserved** across any legal sequence of actions, and through
//!    pot construction and distribution.
//! 2. **Hand ranking is a total order** — and the fast evaluator agrees with
//!    brute force over all five-card subsets.
//! 3. **Side pots sum to total contributions**, whatever the all-in pattern.
//!
//! Hands are drawn by shuffling a real deck from a random seed rather than by
//! generating card bytes and rejecting duplicates, so every generated case is
//! valid by construction and no test time is wasted on rejections.

// Seat indices line up with bitmask positions, so indexed loops read
// better here than iterator adapters.
#![allow(clippy::needless_range_loop)]

use poker_engine::betting::{Action, Betting, LegalActions, Street};
use poker_engine::card::Deck;
use poker_engine::eval::{best_five, evaluate};
use poker_engine::pots::{build_pots, distribute};
use poker_engine::{HandRank, MAX_SEATS};
use proptest::prelude::*;

/// Seven distinct cards drawn off a freshly shuffled deck.
fn seven_cards(seed: &[u8; 32]) -> Vec<u8> {
    Deck::shuffled_from_seed(seed).cards[..7].to_vec()
}

/// Three disjoint seven-card hands from one deck, for transitivity checks.
fn three_hands(seed: &[u8; 32]) -> (Vec<u8>, Vec<u8>, Vec<u8>) {
    let d = Deck::shuffled_from_seed(seed);
    (
        d.cards[0..7].to_vec(),
        d.cards[7..14].to_vec(),
        d.cards[14..21].to_vec(),
    )
}

/// Choose one of the currently legal actions, driven by a generated byte.
fn pick_action(la: &LegalActions, choice: u8) -> Action {
    let mut opts: Vec<Action> = Vec::new();
    if la.can_fold {
        opts.push(Action::Fold);
    }
    if la.can_check {
        opts.push(Action::Check);
    }
    if la.can_call {
        opts.push(Action::Call);
    }
    if la.can_raise {
        opts.push(Action::RaiseTo(la.min_raise_to));
        opts.push(Action::RaiseTo(la.max_raise_to));
        if la.max_raise_to > la.min_raise_to {
            let mid = la.min_raise_to + (la.max_raise_to - la.min_raise_to) / 2;
            opts.push(Action::RaiseTo(mid));
        }
    }
    opts[choice as usize % opts.len()]
}

/// Total chips visible anywhere: behind the seats plus in the middle.
fn chips_in_play(b: &Betting) -> u64 {
    b.seats
        .iter()
        .map(|s| s.stack + s.total_committed)
        .sum::<u64>()
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(512))]

    /// No action, in any order, may create or destroy a chip.
    #[test]
    fn chips_are_conserved_through_any_legal_action_sequence(
        raw_stacks in prop::collection::vec(0u64..2_000, MAX_SEATS),
        button in 0usize..MAX_SEATS,
        choices in prop::collection::vec(any::<u8>(), 1..200),
    ) {
        let mut stacks = [0u64; MAX_SEATS];
        for (i, v) in raw_stacks.iter().enumerate() {
            // Either empty or a meaningful stack; tiny stacks are the
            // interesting case so keep them reachable.
            stacks[i] = if *v < 100 { 0 } else { *v };
        }
        let funded = stacks.iter().filter(|s| **s > 0).count();
        prop_assume!(funded >= 2);

        let starting_total: u64 = stacks.iter().sum();

        let Ok(mut b) = Betting::begin_hand(stacks, button, 5, 10) else {
            return Ok(());
        };
        prop_assert_eq!(chips_in_play(&b), starting_total, "blinds must not mint chips");

        let mut cursor = 0usize;
        let mut guard = 0;
        while b.street != Street::Showdown && !b.hand_is_over() {
            while let Some(seat) = b.to_act {
                let la = b.legal_actions(seat);
                let action = pick_action(&la, choices[cursor % choices.len()]);
                cursor += 1;
                b.apply(seat, action).map_err(|e| {
                    TestCaseError::fail(format!("legal action {action:?} rejected: {e:?}"))
                })?;

                prop_assert_eq!(
                    chips_in_play(&b), starting_total,
                    "chip total changed after {:?} by seat {}", action, seat
                );

                guard += 1;
                prop_assert!(guard < 500, "betting failed to terminate");
            }
            b.advance_street();
            guard += 1;
            prop_assert!(guard < 500, "streets failed to terminate");
        }

        // Nobody may ever commit more than they started with.
        for (i, s) in b.seats.iter().enumerate() {
            prop_assert!(
                s.total_committed <= stacks[i],
                "seat {} committed {} from a stack of {}", i, s.total_committed, stacks[i]
            );
        }

        // Settlement must return exactly what was put in.
        let pots = build_pots(&b.contributions(), &b.folded());
        prop_assert_eq!(pots.total(), b.pot_total(), "pots must hold the whole pot");

        let mut ranks = [None::<HandRank>; MAX_SEATS];
        for (i, s) in b.seats.iter().enumerate() {
            if s.is_in_hand() {
                // Arbitrary but distinct strengths; the exact hands do not
                // matter for conservation.
                ranks[i] = Some(HandRank(1000 + i as u32));
            }
        }
        let dist = distribute(&pots, &ranks, b.button);
        // A real hand always leaves someone unfolded, so nothing may go unowned.
        prop_assert_eq!(
            dist.unclaimed, 0,
            "a played-out hand must never leave unclaimed chips"
        );
        let payouts = dist.payouts;
        prop_assert_eq!(
            payouts.iter().sum::<u64>(), pots.total(),
            "distribution must pay out exactly the pot"
        );

        let final_total: u64 = b.seats.iter()
            .enumerate()
            .map(|(i, s)| s.stack + payouts[i])
            .sum();
        prop_assert_eq!(
            final_total, starting_total,
            "chips at the end must equal chips at the start"
        );
    }

    /// Comparison is a total order: exactly one of <, ==, > holds.
    #[test]
    fn hand_ranking_is_trichotomous(seed in any::<[u8; 32]>()) {
        let (a, b, _) = three_hands(&seed);
        let ra = evaluate(&a);
        let rb = evaluate(&b);
        let lt = ra < rb;
        let eq = ra == rb;
        let gt = ra > rb;
        prop_assert_eq!(
            [lt, eq, gt].iter().filter(|x| **x).count(), 1,
            "exactly one comparison must hold"
        );
    }

    /// Comparison is transitive.
    #[test]
    fn hand_ranking_is_transitive(seed in any::<[u8; 32]>()) {
        let (x, y, z) = three_hands(&seed);
        let mut rs = [evaluate(&x), evaluate(&y), evaluate(&z)];
        rs.sort();
        prop_assert!(rs[0] <= rs[1] && rs[1] <= rs[2]);
        prop_assert!(rs[0] <= rs[2], "sorting must be consistent");
    }

    /// Evaluation depends only on the cards, not the order they arrive in.
    #[test]
    fn evaluation_is_order_independent(seed in any::<[u8; 32]>(), rot in 0usize..7) {
        let cards = seven_cards(&seed);
        let mut rotated = cards.clone();
        rotated.rotate_left(rot);
        prop_assert_eq!(evaluate(&cards), evaluate(&rotated));
    }

    /// A hand's rank never changes if every card keeps its rank but swaps suit
    /// consistently — except where that creates or destroys a flush.
    #[test]
    fn suits_only_matter_through_flushes(seed in any::<[u8; 32]>()) {
        let cards = seven_cards(&seed);
        let r = evaluate(&cards);
        // Force every card to a different suit pattern that cannot make a flush.
        let rainbow: Vec<u8> = cards.iter().enumerate()
            .map(|(i, c)| poker_engine::card::make_card(
                poker_engine::card::rank_of(*c), (i % 4) as u8))
            .collect();
        // Ranks are unchanged, so any difference must come from flushes only.
        let rr = evaluate(&rainbow);
        use poker_engine::Category;
        if r.category() != Category::Flush && r.category() != Category::StraightFlush {
            prop_assert_eq!(
                r.category(), rr.category(),
                "non-flush categories must not depend on suits"
            );
        }
    }
}

proptest! {
    // The brute-force cross-check is the strongest correctness statement in the
    // crate, so it gets more cases than the rest.
    #![proptest_config(ProptestConfig::with_cases(2_000))]

    /// The fast table-free evaluator must agree with exhaustive search over all
    /// 21 five-card subsets of the seven cards.
    #[test]
    fn fast_evaluator_matches_brute_force(seed in any::<[u8; 32]>()) {
        let cards = seven_cards(&seed);
        let fast = evaluate(&cards);
        let (_, slow) = best_five(&cards);
        prop_assert_eq!(
            fast, slow,
            "fast path disagreed on {}", poker_engine::card::cards_to_string(&cards)
        );
    }
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(1_024))]

    /// Pots always account for every chip contributed, however the all-ins fall.
    #[test]
    fn pots_always_sum_to_contributions(
        raw in prop::collection::vec(0u64..1_000, MAX_SEATS),
        fold_bits in any::<u8>(),
    ) {
        let mut contributions = [0u64; MAX_SEATS];
        contributions.copy_from_slice(&raw);
        let mut folded = [false; MAX_SEATS];
        for i in 0..MAX_SEATS {
            folded[i] = fold_bits & (1 << i) != 0;
        }

        let pots = build_pots(&contributions, &folded);
        prop_assert_eq!(
            pots.total(), contributions.iter().sum::<u64>(),
            "pot layers must sum to what was contributed"
        );

        // A folded seat can never be eligible for any layer.
        for pot in pots.iter() {
            for seat in 0..MAX_SEATS {
                if folded[seat] {
                    prop_assert!(
                        !pot.is_eligible(seat),
                        "folded seat {} was eligible for a pot", seat
                    );
                }
            }
        }

        // Eligibility shrinks monotonically as layers get deeper: a seat
        // eligible for a later pot must be eligible for every earlier one.
        let layers: Vec<_> = pots.iter().collect();
        for w in layers.windows(2) {
            for seat in 0..MAX_SEATS {
                if w[1].is_eligible(seat) {
                    prop_assert!(
                        w[0].is_eligible(seat),
                        "seat {} skipped a pot layer", seat
                    );
                }
            }
        }
    }

    /// Distribution pays out exactly the pot, never more or less.
    #[test]
    fn distribution_conserves_chips(
        raw in prop::collection::vec(0u64..1_000, MAX_SEATS),
        fold_bits in any::<u8>(),
        rank_seed in prop::collection::vec(0u32..50, MAX_SEATS),
        button in 0usize..MAX_SEATS,
    ) {
        let mut contributions = [0u64; MAX_SEATS];
        contributions.copy_from_slice(&raw);
        let mut folded = [false; MAX_SEATS];
        for i in 0..MAX_SEATS {
            folded[i] = fold_bits & (1 << i) != 0;
        }
        // Every unfolded contributor shows a hand, as it would at showdown.
        let mut ranks = [None::<HandRank>; MAX_SEATS];
        for i in 0..MAX_SEATS {
            if !folded[i] && contributions[i] > 0 {
                // Deliberately coarse so ties are common.
                ranks[i] = Some(HandRank(rank_seed[i]));
            }
        }

        let pots = build_pots(&contributions, &folded);
        let dist = distribute(&pots, &ranks, button);
        let payouts = dist.payouts;

        // Inputs here are arbitrary, so a layer may legitimately have no live
        // claimant. Chips must still be fully accounted for.
        prop_assert_eq!(
            payouts.iter().sum::<u64>() + dist.unclaimed, pots.total(),
            "payouts plus unclaimed must equal the pot exactly"
        );

        // Unclaimed chips only ever come from layers nobody was eligible for.
        if dist.unclaimed > 0 {
            prop_assert!(
                pots.iter().any(|p| p.eligible == 0 && p.amount > 0),
                "unclaimed chips must trace to a layer with no eligible seat"
            );
        }

        // Nobody wins a layer they were not eligible for.
        for seat in 0..MAX_SEATS {
            if payouts[seat] > 0 {
                prop_assert!(
                    pots.iter().any(|p| p.is_eligible(seat)),
                    "seat {} was paid without being eligible for anything", seat
                );
            }
        }
    }
}
