[package]
name = "solpoker"
version = "0.1.0"
description = "Real-time on-chain Texas Hold'em with TEE-protected hole cards"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solpoker"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
custom-heap = []
custom-panic = []
anchor-debug = []

[dependencies]
anchor-lang = { version = "=1.0.2", features = ["init-if-needed"] }
ephemeral-rollups-sdk = { version = "0.16.2", features = ["anchor"] }
session-keys = { version = "=3.1.1", features = ["no-entrypoint"] }
poker-engine = { path = "../../crates/poker-engine" }
